# Generated by Django 2.1 on 2018-08-11 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTransaccion', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('nombreMoneda', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('signo', models.CharField(max_length=8)),
                ('peso', models.IntegerField(default=0)),
                ('espesor', models.FloatField(default=0.0)),
                ('fechaCreacion', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MonedasUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantMonedas', models.IntegerField(default=0)),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monedas.Moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombreUsuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(default='', max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('last_login', models.DateField(default=datetime.datetime(2018, 8, 11, 14, 5, 56, 873144))),
            ],
        ),
        migrations.AddField(
            model_name='monedasusuario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monedas.Usuario'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='creadaPor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monedas.Usuario'),
        ),
        migrations.AddField(
            model_name='historial',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monedas.Moneda'),
        ),
        migrations.AddField(
            model_name='historial',
            name='usuarioEnvia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioEnvia', to='monedas.Usuario'),
        ),
        migrations.AddField(
            model_name='historial',
            name='usuarioRecibe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioRecibe', to='monedas.Usuario'),
        ),
    ]
