# Generated by Django 2.1 on 2018-08-05 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='espesor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='moneda',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='moneda',
            name='peso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombreMoneda',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombreUsuario',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
