# Generated by Django 2.1 on 2018-08-11 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0002_auto_20180811_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2018, 8, 11, 15, 27, 58, 224433)),
        ),
    ]
