# Generated by Django 2.1 on 2018-08-08 01:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0003_auto_20180805_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTransaccion', models.DateTimeField(default=datetime.datetime.now)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monedas.Moneda')),
                ('usuarioEnvia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioEnvia', to='monedas.Usuario')),
                ('usuarioRecibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioRecibe', to='monedas.Usuario')),
            ],
        ),
    ]
