# Generated by Django 2.1 on 2018-08-12 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0003_auto_20180811_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monedasusuario',
            old_name='id_moneda',
            new_name='moneda',
        ),
        migrations.RenameField(
            model_name='monedasusuario',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2018, 8, 12, 23, 53, 48, 779126)),
        ),
    ]
