# Generated by Django 2.1 on 2018-08-13 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0005_auto_20180813_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='cantMonedas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2018, 8, 13, 3, 58, 11, 104966)),
        ),
    ]
