# Generated by Django 2.1 on 2018-08-14 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0006_auto_20180813_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='usuarioCreador',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='moneda',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='usuarioEnvia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='usuarioRecibe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2018, 8, 14, 10, 6, 51, 280156)),
        ),
    ]
